require 'active_record'
require 'active_support'
require 'activerecord-decimal-datetime-adapter/version'
require 'activerecord-decimal-datetime-adapter/date'
#require 'activerecord-decimal-datetime-adapter/time'
